/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KolegijController;
import controller.UsersController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Kolegij;
import model.Users;

/**
 *
 * @author Admin
 */
public class DialogPovezivanjeProfesoraIKolegija extends javax.swing.JDialog {

    
    KolegijController controllerKolegij = new KolegijController();
    UsersController controllerUsers = new UsersController();
    /**
     * Creates new form DialogPovezivanjeProfesoraIKolegija
     */
    public DialogPovezivanjeProfesoraIKolegija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preuzimanjeSvihKolegija();
        preuzimanjeProfesora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSpremi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbKolegiji = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbProfesori = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos nositelja kolegija - Administrator");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Unos nositelja za kolegij"));

        btnSpremi.setText("Spremi");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        jLabel3.setText("Odaberite kolegij");

        cmbKolegiji.setModel(new javax.swing.DefaultComboBoxModel<>());
        cmbKolegiji.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKolegijiItemStateChanged(evt);
            }
        });
        cmbKolegiji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKolegijiActionPerformed(evt);
            }
        });

        jLabel1.setText("Odaberite nositelja");

        cmbProfesori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProfesoriItemStateChanged(evt);
            }
        });
        cmbProfesori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProfesoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmbKolegiji, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSpremi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbKolegiji, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSpremi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     private void preuzimanjeSvihKolegija() {
        System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|preuzimanjeSvihKolegija");
        cmbKolegiji.removeAllItems();
        List<Kolegij> lista;

        try {
            lista = (List<Kolegij>) controllerKolegij.listaKolegija1();
            lista.stream().forEach((i) -> {
                cmbKolegiji.addItem(i);
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška broj 1", "Kritična Greška", JOptionPane.ERROR_MESSAGE);
            System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|preuzimanjeSvihKolegija|Exception|" + e.toString());
            return;
        }

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Svi kolegiji imaju nositelja.", "Obavijest", JOptionPane.PLAIN_MESSAGE);
            System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|preuzimanjeSvihKolegija|Prazna lista");
        }
    }
     
      private void preuzimanjeProfesora() {
        
        cmbProfesori.removeAllItems();
        List<Users> lista;
        

        try {
            lista = (List<Users>) controllerUsers.listaProfesora();
            
            lista.stream().forEach((i) -> {
                cmbProfesori.addItem(i);
            });
            System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|preuzimanjeProfesora|USPJESAN");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška"+e, "Kritična Greška", JOptionPane.ERROR_MESSAGE);
            System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|preuzimanjeProfesora|Exception|" + e.toString());
            return;
        }

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nema profesora u bazi podataka!!!!.", "Obavijest", JOptionPane.PLAIN_MESSAGE);
            System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|preuzimanjeProfesora|Prazna lista|Nema termina za taj kolegij");
        }
    }
     
    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed


        if (cmbKolegiji.getSelectedItem()==null || cmbProfesori.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(this,"Niste odabrali sva polja za unos .","Upozorenje",JOptionPane.WARNING_MESSAGE);
            System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|spremanjeNositeljaKolegija|Prazno polje");
            return;
        }

        try {
            
            Kolegij odabraniKolegij = (Kolegij) cmbKolegiji.getSelectedItem();
            Users odabraniUsers =(Users) cmbProfesori.getSelectedItem();

            controllerUsers.unosNositelja(odabraniKolegij, odabraniUsers);
           
            preuzimanjeSvihKolegija();
            preuzimanjeProfesora();
        } catch (Exception ex) {
            Logger.getLogger(DialogUnosKolegija.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("DEBUG|DialogPovezivanjeProfesoraIKolegija|spremanjeNositeljaKolegija|Greska"+ex);
        }

    }//GEN-LAST:event_btnSpremiActionPerformed

    private void cmbKolegijiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKolegijiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKolegijiItemStateChanged

    private void cmbKolegijiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKolegijiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKolegijiActionPerformed

    private void cmbProfesoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProfesoriItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProfesoriItemStateChanged

    private void cmbProfesoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProfesoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProfesoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogPovezivanjeProfesoraIKolegija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogPovezivanjeProfesoraIKolegija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogPovezivanjeProfesoraIKolegija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogPovezivanjeProfesoraIKolegija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogPovezivanjeProfesoraIKolegija dialog = new DialogPovezivanjeProfesoraIKolegija(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpremi;
    private javax.swing.JComboBox<Kolegij> cmbKolegiji;
    private javax.swing.JComboBox<Users> cmbProfesori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
